name: Changelog Generation
on:
  push:
    branches:
      - main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      # ios, Android 버전 변경 시 해당 태그 가져오기
      - name: Npm Tag
        id: "npm_tag"
        run: node ./bin/getTag.js

      # ios 버전 변경 시 해당 태그 생성
      - name: "Push IOS tag v${{ steps.npm_tag.outputs.ios_version }}"
        uses: rickstaa/action-create-tag@v1
        id: ios_tag_version
        with:
          tag: "ios_${{ steps.npm_tag.outputs.ios_version }}"

      - name: Configure changelog
        run: |
          cat << 'EOF' > changelog_config.json
          {
            "categories": [],
            "template": "## Commits\n\n{{UNCATEGORIZED}}",
            "pr_template": "- {{MERGE_SHA}} {{TITLE}}"
          }
          EOF

          cat changelog_config.json

          echo "last_tag=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_ENV

      # ios changelog 생성
      # - name: Generate ios Tag
      #   id: ios_github_release
      #   uses: mikepenz/release-changelog-builder-action@v2.9.0
      #   if: steps.npm_tag.outputs.ios_version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     fromTag: "ios_${{ steps.npm_tag.outputs.ios_version }}"
      #     toTag: "ios_1.0.0"
      #     configuration: change_ios_log_config.json

      - name: Build Changelog
        id: ios_github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitMode: true
          fromTag: "ios_1.0.0"
          toTag: "ios_${{ steps.npm_tag.outputs.ios_version }}"
          configuration: change_ios_log_config.json

      - name: Write changelog to file
        run: |
          echo "## v${{ steps.npm_tag.outputs.ios_version }} - $(date +'%Y-%m-%d')" >> IOS_CHANGELOG.md
          echo "" >> IOS_CHANGELOG.md
          echo "${{ steps.ios_github_release.outputs.changelog }}" >> IOS_CHANGELOG.md
          echo "" >> IOS_CHANGELOG.md
          cat IOS_CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add IOS_CHANGELOG.md
          git commit -m "docs(changelog): v${{ steps.npm_tag.outputs.ios_version }}"
          git push

      # # Android 버전 변경 시 해당 태그 생성
      # - name: "Push Android tag v${{ steps.npm_tag.outputs.android_version }}"
      #   uses: rickstaa/action-create-tag@v1
      #   id: android_tag_version
      #   with:
      #     tag: "android_${{ steps.npm_tag.outputs.android_version }}"
      # # android changelog 생성
      # - name: Generate Android Tag
      #   id: android_github_release
      #   uses: mikepenz/release-changelog-builder-action@v2.9.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   if: steps.npm_tag.outputs.android_version
      #   with:
      #     fromTag: "android_${{ steps.npm_tag.outputs.android_version }}"
      #     toTag: "android_${{ github.ref }}"
      #     commitMode: true
      #     configuration: change_ios_log_config.json
