name: Changelog Generation
on:
  push:
    branches:
      - main
jobs:
  record-logs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - name: Npm Tag
        id: "new_tag"
        run: node ./bin/getTag.js

      - name: Get last tags
        id: last_tags
        run: |
          LAST_IOS=$(git tag --list 'ios_*' --sort=-creatordate | head -n 1)
          LAST_ANDROID=$(git tag --list 'android_*' --sort=-creatordate | head -n 1)

          echo "Last IOS Tag: $LAST_IOS"
          echo "Last Android Tag: $LAST_ANDROID"

          echo "last_ios_tag=$LAST_IOS" >> $GITHUB_ENV
          echo "last_android_tag=$LAST_ANDROID" >> $GITHUB_ENV

      # IOS Changelog
      - name: "Push IOS tag v${{ steps.new_tag.outputs.ios_version }}"
        uses: rickstaa/action-create-tag@v1
        if: ${{ steps.new_tag.outputs.ios_version != steps.last_tags.outputs.last_ios_tag }}
        id: ios_tag_version
        with:
          tag: "${{ steps.new_tag.outputs.ios_version }}"

      - name: Configure changelog
        if: ${{ steps.new_tag.outputs.ios_version != steps.last_tags.outputs.last_ios_tag }}
        run: |
          cat << 'EOF' > changelog_config.json
          {
            "categories": [],
            "template": "## Commits\n\n{{COMMITS}}",
            "commit_template": "- {{SHORT_SHA}} {{TITLE}}"
          }
          EOF
          echo "last_tag=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_ENV

      - name: Build Changelog
        id: ios_github_release
        uses: mikepenz/release-changelog-builder-action@v5
        if: ${{ steps.new_tag.outputs.ios_version != steps.last_tags.outputs.last_ios_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commitMode: true
          fromTag: "${{ steps.last_tags.outputs.last_ios_tag }}"
          toTag: "${{ steps.new_tag.outputs.ios_version }}"
          configuration: change_ios_log_config.json

      - name: Write changelog to file
        if: ${{ steps.new_tag.outputs.ios_version != steps.last_tags.outputs.last_ios_tag }}
        run: |
          echo "## v${{ steps.new_tag.outputs.ios_version }} - $(date +'%Y-%m-%d')" >> IOS_CHANGELOG.md
          echo "" >> IOS_CHANGELOG.md
          echo "${{ steps.ios_github_release.outputs.changelog }}" >> IOS_CHANGELOG.md
          echo "" >> IOS_CHANGELOG.md
          cat IOS_CHANGELOG.md

      - name: Commit changelog
        if: ${{ steps.new_tag.outputs.ios_version != steps.last_tags.outputs.last_ios_tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add IOS_CHANGELOG.md
          git commit -m "docs(changelog): v${{ steps.new_tag.outputs.ios_version }}"
          git push

      # Android Changelog
